name: Prueba contador

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Preparar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Ejecutar script
        run: python contador.py

      - name: Guardar cambios
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "actualizacion"
          git push